image: golang:latest

stages:
  - test
  - build

test:
  stage: test
  coverage: '/coverage: \d+.\d+% of statements/'
  script:
    - go test -v -race -cover ./...

golangci-lint:
  stage: test
  image:
    name: golangci/golangci-lint:latest
    entrypoint: [""]
  script:
    - golangci-lint run ./...

build:
  stage: build
  before_script:
    - go mod download
  script:
    - find cmd -type d -mindepth 1 -maxdepth 1 -exec go build ./{}/... \;
  artifacts:
    untracked: true
