image: golang:latest

stages:
  - test
  - build
  - download-itemdb
  - deploy

.go-generate: &go-generate
  before_script:
    - go mod download && go install golang.org/x/tools/cmd/stringer
    - go generate ./...

test:
  stage: test
  coverage: '/total:\s+\(statements\)\s+(\d+.\d+\%)/'
  <<: *go-generate
  script:
    - go test -race $(go list ./lib/... | grep -v /vendor/) -v -coverprofile=coverage.out
    - go tool cover -func=coverage.out

golangci-lint:
  stage: test
  image:
    name: golangci/golangci-lint:latest
    entrypoint: [""]
  <<: *go-generate
  script:
    - golangci-lint run --timeout 5m ./...

build:
  stage: build
  <<: *go-generate
  script:
    - find cmd -type d -mindepth 1 -maxdepth 1 -exec go build ./{}/... \;
  artifacts:
    untracked: true

download-itemdb:
  stage: download-itemdb
  tags:
    - external
  only:
    - schedules
  dependencies:
    - build
  script:
    - ./rs-cli itemdb download -f ./items.ljson
  artifacts:
    paths:
      - ./items.ljson

pages:
  stage: deploy
  tags:
    - external
  only:
    - schedules
  dependencies:
    - download-itemdb
  script:
    - mkdir public
    - cp items.ljson public/
  artifacts:
    paths:
      - public