image: golang:latest

stages:
  - test
  - build
  - download-itemdb
  - deploy

.go-generate: &go-generate
  before_script:
    - go mod download && go install golang.org/x/tools/cmd/stringer
    - go generate ./...

test:
  stage: test
  coverage: '/total:\s+\(statements\)\s+(\d+.\d+\%)/'
  <<: *go-generate
  script:
    - go test -race $(go list ./lib/... | grep -v /vendor/) -v -coverprofile=coverage.out
    - go tool cover -func=coverage.out

golangci-lint:
  stage: test
  image:
    name: golangci/golangci-lint:latest
    entrypoint: [""]
  <<: *go-generate
  script:
    - golangci-lint run --timeout 5m ./...

build:
  stage: build
  <<: *go-generate
  script:
    - find cmd -type d -mindepth 1 -maxdepth 1 -exec go build ./{}/... \;
  artifacts:
    untracked: true

build-image:
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:v1.9.0-debug
    entrypoint: [""]
  script:
    - /kaniko/executor
      --context "${CI_PROJECT_DIR}"
      --dockerfile "${CI_PROJECT_DIR}/Dockerfile"
      --destination "${CI_REGISTRY_IMAGE}:${CI_COMMIT_TAG}"

download-itemdb:
  stage: download-itemdb
  tags:
    - external
  only:
    - schedules
  dependencies:
    - build
  before_script:
    - wget https://schoentoon.gitlab.io/rs-tools/items.ljson
    - wget https://schoentoon.gitlab.io/rs-tools/meta.json
  script:
    - ./rs-cli itemdb download -f ./items.ljson -m meta.json
  artifacts:
    paths:
      - ./items.ljson
      - ./meta.json

pages:
  stage: deploy
  only:
    - schedules
  dependencies:
    - download-itemdb
  script:
    - mkdir public
    - cp items.ljson meta.json public/
  artifacts:
    paths:
      - public